Changed in 2017-01-24

diff --git a/jansson/jansson.SlackBuild b/jansson/jansson.SlackBuild
--- a/jansson/jansson.SlackBuild
+++ b/jansson/jansson.SlackBuild
@@ -28,42 +28,43 @@
 # 
 #
 #
-# Official Site: http://telegram.org
+# Official Site: http://www.digip.org/jansson/
 #
 
 # Set variables:
 CWD=`pwd`
 OUTPUT=${OUTPUT:-$CWD}
-PKGNAME=telegram
+PKGNAME=jansson
 TMP=${TMP:-/tmp/txz/$PKGNAME}
 PKG=$TMP/package
-VERSION=${VERSION:-1.0.2}
+VERSION=${VERSION:-2.9}
 ARCH=${ARCH:-$(uname -m)}
 JOBS=${JOBS:--j5}
 BUILD=${BUILD:-1}
 TAG=${TAG:-sm}
+SUFFIX=${SUFFIX:-tar.bz2}
 
-case "$ARCH" in
-  x86_64)
-    SRC=""
-    ;;
-  i486)
-    SRC="32"
-    ;;
-  *)
-    echo "$ARCH is not supported."
-    exit 1
-    ;;
-esac
-
-SOURCE="https://updates.tdesktop.com/tlinux${SRC}/tsetup${SRC}.${VERSION}.tar.xz"
+SOURCE="http://www.digip.org/$PKGNAME/releases/$PKGNAME-$VERSION.$SUFFIX"
 
 TAR=${TAR:-$(basename $SOURCE)}
 DIR=${DIR:-$(echo "$TAR"|sed -r 's/(\.tar|)(.gz|.bz2|.xz|.tgz|)$//')}
 
+if [ ! -e $CWD/$TAR ]; then
+    echo -e "[\033[01;32m  Download source tarball  \033[01;37m] "
+    echo ""
+    echo ""
+    sleep 2
+fi
+
 # Download source tarball if still not present
 if [ ! -e $CWD/$TAR ]; then
    wget -c $SOURCE -O "$CWD/$TAR" || exit 1
+fi
+
+FILE=$SOURCE
+if [ -e "$FILE" ] ; then
+   echo -e "[\033[01;31m  Tarball not found  \033[01;37m]"
+   exit 1
 fi
 
 # Set compiling FLAGS
@@ -88,19 +89,45 @@ fi
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT 
 
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "[\033[01;32m  Decompress the source tarball  \033[01;37m] "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+sleep 2
+
 # Decompress the source tarball
 cd $TMP
 tar xvf $CWD/$TAR || exit 1
-cd Telegram || exit 1
+cd $DIR || exit 1
 
-echo -e "\E[0;32m#####                              \E[0;0m"
-echo -e "\E[0;32m+++++ Start SlackBuild $PKGNAME    \E[0;0m"
-echo -e "\E[0;32m#####                              \E[0;0m"
+# Apply some patches
+#patch -p1 < $CWD/patches/Makefile.patch --verbose || exit 1
+
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "[\033[01;32m  Building  package  \033[01;37m] "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+sleep 2
 
 # Building  package
-
-mkdir -p $PKG/usr/bin
-cp -a * $PKG/usr/bin
+LDFLAGS="$SLKLDFLAGS" \
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
+     ./configure \
+        --prefix=/usr \
+        --libdir=/usr/lib${LIBDIRSUFFIX} \
+        --sysconfdir=/etc \
+        --localstatedir=/var \
+        --mandir=/usr/man \
+        --docdir=/usr/doc/$PRGNAM-$VERSION \
+        --enable-static=no \
+        --disable-silent-rules \
+		--build=$CHOST-slackware-linux || exit 1
+		
+make $JOBS 2>&1 | tee build.log || exit 1
+make install DESTDIR=$PKG || exit 1
 
 # Strip binaries and shared objects, if present
 ( cd $PKG
@@ -108,12 +135,6 @@ cp -a * $PKG/usr/bin
   find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
   find . | xargs file | grep "current ar archive" | cut -f 1 -d : | xargs -r strip --strip-unneeded 2> /dev/null || true
 )
-
-mkdir -p $PKG/usr/share/applications
-cat $CWD/$PKGNAME.desktop > $PKG/usr/share/applications/$PKGNAME.desktop
-
-mkdir -p $PKG/usr/share/pixmaps
-cp $CWD/$PKGNAME.png $PKG/usr/share/pixmaps
 
 # Also add the slack-desk file to the package
 mkdir -p $PKG/install
@@ -135,16 +156,6 @@ if [ -x $CWD/patches ];then
    chmod 644 $PKG/usr/doc/$PKGNAME-$VERSION/SlackBuild/patches/*
 fi
 
-# Building some post-install execution script 	
-	echo "if [ -x /usr/bin/update-desktop-database ]; then
-  /usr/bin/update-desktop-database &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-	echo "if [ -x /usr/bin/gtk-update-icon-cache ]; then
-  /usr/bin/gtk-update-icon-cache  -f -q /usr/share/icons/hicolor &> /dev/null
-fi" >> $PKG/install/doinst.sh
-	echo "" >> $PKG/install/doinst.sh
-
 # Compress the man pages if present
 if [ -d $PKG/usr/man ]; then
     ( cd $PKG/usr/man
@@ -152,6 +163,19 @@ if [ -d $PKG/usr/man ]; then
       for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
     )
 fi
+
+# Find and print dependencies into slack-required file
+cd $PKG
+if [ -x /usr/bin/requiredbuilder ];then
+   requiredbuilder -y -v -b -s  $CWD $PKG
+fi
+
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "[\033[01;32m  Create txz package  \033[01;37m] "
+echo -e "\033[01;32m  \033[01;37m "
+echo -e "\033[01;32m  \033[01;37m "
+sleep 2
 
 # Create txz package
 ROOTCOMMANDS="set -o errexit -o xtrace ; cd ${PKG} ;
